version: "3.8"
services:
  web:
    build: ./app
    image: 772227205276.dkr.ecr.us-east-1.amazonaws.com/exercise-1:workshop1_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django-data:/var/lib/django/data
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=my_tutorials
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=exercise-db.c7dqswqkkr5e.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-54-161-245-133.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
    depends_on:
      - pg
  pg:
    container_name: pg_container2
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_tutorials
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container2
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
volumes:
  django-data:
  postgres-data:


